### ISSUE TITLE
TrackMateImporter.saveTo wants to use unavailable settings.xstart

### ISSUE THREAD

**Issue by manerotoni** [tinevez/TrackMate-CSVImporter#2]
With the new update of TrackMate (7.7.1) some dependencies seems to have been broken.

The Importer `TrackMateImporter.java` tries to access (line 510)

`settings.xstart = 0;`

but the settings value seems to be absent and I get following error

`	at fiji.plugin.trackmate.importer.csv.TrackMateImporter.createSettingsFromImageFile(TrackMateImporter.java:510)
	at fiji.plugin.trackmate.importer.csv.TrackMateImporter.createSettingsFromImageFile(TrackMateImporter.java:465)
	at fiji.plugin.trackmate.importer.csv.TrackMateImporter.getSettings(TrackMateImporter.java:204)
	at fiji.plugin.trackmate.importer.csv.TrackMateImporter.saveTo(TrackMateImporter.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NoSuchFieldError: java.lang.NoSuchFieldError: xstart`

**Comment by tinevez** [comment]
Hello. I just released the v3.1.1 version that was uploaded to Fiji now.
Can you test that it works for you as well?

**Comment by manerotoni** [comment]
Yes it seems to work. Thanks!
